# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fakedetect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fakedetect.proto',
  package='fakedetectorapi',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x66\x61kedetect.proto\x12\x0f\x66\x61kedetectorapi\"(\n\x14\x43heckUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\'\n\x15\x43heckUsernameResponse\x12\x0e\n\x06isFake\x18\x01 \x01(\x08\"*\n\x15\x43heckUsernamesRequest\x12\x11\n\tusernames\x18\x01 \x03(\t\"/\n\x16\x43heckUsernamesResponse\x12\x15\n\rfakeUsernames\x18\x01 \x03(\t2\xd8\x01\n\x13\x46\x61keDetectorService\x12^\n\rCheckUsername\x12%.fakedetectorapi.CheckUsernameRequest\x1a&.fakedetectorapi.CheckUsernameResponse\x12\x61\n\x0e\x43heckUsernames\x12&.fakedetectorapi.CheckUsernamesRequest\x1a\'.fakedetectorapi.CheckUsernamesResponseb\x06proto3'
)




_CHECKUSERNAMEREQUEST = _descriptor.Descriptor(
  name='CheckUsernameRequest',
  full_name='fakedetectorapi.CheckUsernameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='fakedetectorapi.CheckUsernameRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=77,
)


_CHECKUSERNAMERESPONSE = _descriptor.Descriptor(
  name='CheckUsernameResponse',
  full_name='fakedetectorapi.CheckUsernameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isFake', full_name='fakedetectorapi.CheckUsernameResponse.isFake', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=118,
)


_CHECKUSERNAMESREQUEST = _descriptor.Descriptor(
  name='CheckUsernamesRequest',
  full_name='fakedetectorapi.CheckUsernamesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usernames', full_name='fakedetectorapi.CheckUsernamesRequest.usernames', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=162,
)


_CHECKUSERNAMESRESPONSE = _descriptor.Descriptor(
  name='CheckUsernamesResponse',
  full_name='fakedetectorapi.CheckUsernamesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fakeUsernames', full_name='fakedetectorapi.CheckUsernamesResponse.fakeUsernames', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['CheckUsernameRequest'] = _CHECKUSERNAMEREQUEST
DESCRIPTOR.message_types_by_name['CheckUsernameResponse'] = _CHECKUSERNAMERESPONSE
DESCRIPTOR.message_types_by_name['CheckUsernamesRequest'] = _CHECKUSERNAMESREQUEST
DESCRIPTOR.message_types_by_name['CheckUsernamesResponse'] = _CHECKUSERNAMESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CheckUsernameRequest = _reflection.GeneratedProtocolMessageType('CheckUsernameRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKUSERNAMEREQUEST,
  '__module__' : 'fakedetect_pb2'
  # @@protoc_insertion_point(class_scope:fakedetectorapi.CheckUsernameRequest)
  })
_sym_db.RegisterMessage(CheckUsernameRequest)

CheckUsernameResponse = _reflection.GeneratedProtocolMessageType('CheckUsernameResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKUSERNAMERESPONSE,
  '__module__' : 'fakedetect_pb2'
  # @@protoc_insertion_point(class_scope:fakedetectorapi.CheckUsernameResponse)
  })
_sym_db.RegisterMessage(CheckUsernameResponse)

CheckUsernamesRequest = _reflection.GeneratedProtocolMessageType('CheckUsernamesRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKUSERNAMESREQUEST,
  '__module__' : 'fakedetect_pb2'
  # @@protoc_insertion_point(class_scope:fakedetectorapi.CheckUsernamesRequest)
  })
_sym_db.RegisterMessage(CheckUsernamesRequest)

CheckUsernamesResponse = _reflection.GeneratedProtocolMessageType('CheckUsernamesResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKUSERNAMESRESPONSE,
  '__module__' : 'fakedetect_pb2'
  # @@protoc_insertion_point(class_scope:fakedetectorapi.CheckUsernamesResponse)
  })
_sym_db.RegisterMessage(CheckUsernamesResponse)



_FAKEDETECTORSERVICE = _descriptor.ServiceDescriptor(
  name='FakeDetectorService',
  full_name='fakedetectorapi.FakeDetectorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=214,
  serialized_end=430,
  methods=[
  _descriptor.MethodDescriptor(
    name='CheckUsername',
    full_name='fakedetectorapi.FakeDetectorService.CheckUsername',
    index=0,
    containing_service=None,
    input_type=_CHECKUSERNAMEREQUEST,
    output_type=_CHECKUSERNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckUsernames',
    full_name='fakedetectorapi.FakeDetectorService.CheckUsernames',
    index=1,
    containing_service=None,
    input_type=_CHECKUSERNAMESREQUEST,
    output_type=_CHECKUSERNAMESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAKEDETECTORSERVICE)

DESCRIPTOR.services_by_name['FakeDetectorService'] = _FAKEDETECTORSERVICE

# @@protoc_insertion_point(module_scope)
