# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fakedetect_pb2 as fakedetect__pb2


class FakeDetectorServiceStub(object):
    """service definition for the Fake Detector service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckUsername = channel.unary_unary(
                '/fakedetectorapi.FakeDetectorService/CheckUsername',
                request_serializer=fakedetect__pb2.CheckUsernameRequest.SerializeToString,
                response_deserializer=fakedetect__pb2.CheckUsernameResponse.FromString,
                )
        self.CheckUsernames = channel.unary_unary(
                '/fakedetectorapi.FakeDetectorService/CheckUsernames',
                request_serializer=fakedetect__pb2.CheckUsernamesRequest.SerializeToString,
                response_deserializer=fakedetect__pb2.CheckUsernamesResponse.FromString,
                )


class FakeDetectorServiceServicer(object):
    """service definition for the Fake Detector service
    """

    def CheckUsername(self, request, context):
        """check single username
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUsernames(self, request, context):
        """check multiple usernames
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FakeDetectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUsername,
                    request_deserializer=fakedetect__pb2.CheckUsernameRequest.FromString,
                    response_serializer=fakedetect__pb2.CheckUsernameResponse.SerializeToString,
            ),
            'CheckUsernames': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUsernames,
                    request_deserializer=fakedetect__pb2.CheckUsernamesRequest.FromString,
                    response_serializer=fakedetect__pb2.CheckUsernamesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fakedetectorapi.FakeDetectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FakeDetectorService(object):
    """service definition for the Fake Detector service
    """

    @staticmethod
    def CheckUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fakedetectorapi.FakeDetectorService/CheckUsername',
            fakedetect__pb2.CheckUsernameRequest.SerializeToString,
            fakedetect__pb2.CheckUsernameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUsernames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fakedetectorapi.FakeDetectorService/CheckUsernames',
            fakedetect__pb2.CheckUsernamesRequest.SerializeToString,
            fakedetect__pb2.CheckUsernamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
